Repository Team-Hankki/hankki-iOS, pull requests merged in 2024-06, with the labels that each got.

#3 [Setting] #1 - 초기세팅
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/AppDelegate.swift
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/MainButton.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/FontLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/ImageLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/NSObject+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIButton+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIColor+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UILabel+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIStackView+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UITextField+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Protocols/AuthenticationAdapterProtocol.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Base.lproj/LaunchScreen.storyboard
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/a.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Network/Home/DTO/Request/request.swift
  Hankkijogbo/Hankkijogbo/Network/Home/DTO/Response/response.swift
  Hankkijogbo/Hankkijogbo/Network/Home/HomeAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Home/HomeTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/Model/HomeModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/ViewController.swift
Labels: ⚙️ Setting, 💞 가현

#4 [Setting] #2 - 리드미 작성
  README.md
Labels: 📄 Docs, 🤹🏻‍♀️ 서현

#6 [Setting] #5 - swiftlint 및 Base 파일 세팅
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/.swiftlint.yml
  Hankkijogbo/Hankkijogbo/Present/Base/BaseCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseModel.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
Labels: ⚙️ Setting, 🐬 은수

#7 [Setting] #2 - 리드미 수정 (라이브러리 사용 이유 추가)
  README.md
Labels: 📄 Docs, 🤹🏻‍♀️ 서현
