Repository Team-Hankki/hankki-iOS, pull requests merged in 2024-10, with the labels that each got.

#258 [Feat] #253 - 메뉴 추가 및 편집 바텀 시트 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_add_menu.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_add_menu.imageset/ic_add_menu.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_edit_menu.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_edit_menu.imageset/ic_edit_menu.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add.imageset/img_add.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add.imageset/img_add@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add.imageset/img_add@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_edit.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_edit.imageset/img_edit.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_edit.imageset/img_edit@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_edit.imageset/img_edit@3x.png
  Hankkijogbo/Hankkijogbo/Present/EditHankki/EditHankkiBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
Labels: 🍚 Feat, 🐬 은수

#263 [Design] #262 - Mypage 2차 스프린트 디자인 수정사항 반영
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_arrow_right.imageset/ic_arrow_right.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_heart_red.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_heart_red.imageset/ic_heart.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/myzip/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/myzip/ic_mypage_liked.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/myzip/ic_mypage_liked.imageset/ic_myheart.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/myzip/ic_mypage_myzip.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/myzip/ic_mypage_myzip.imageset/ic_myjokbo.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/myzip/ic_mypage_reported.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/myzip/ic_mypage_reported.imageset/ic_newjaebo.svg
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHankkiCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageSeparatorView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageZipCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
Labels: 🎨 Design, 🤹🏻‍♀️ 서현

#266 [Feat] #259 - 메뉴 추가 UI 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/BottomButtonView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add_complete.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add_complete.imageset/img.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add_complete.imageset/img@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_add_complete.imageset/img@3x.png
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/DTO/PostMenuResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/MenuAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/MenuTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/EditHankki/View/AddNewMenuCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/EditHankki/View/AddNewMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/EditHankki/View/EditHankkiBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/EditHankki/ViewModel/AddNewMenuViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/AddMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportCompositionalLayoutFactory.swift
  Hankkijogbo/Hankkijogbo/Present/ViewController.swift
Labels: 🍚 Feat, 🐬 은수

#270 [Feat] #269 - 둘러보기 로그인유저 식별 로직 추가
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#271 [Feat] #267 - 둘러보기 로그인 유도 Alert 구현
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🍚 Feat, 💞 가현

#275 [Feat] #274 - 둘러보기 기능 추가
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResultDelegate.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: 🍚 Feat, 💞 가현

#277 [Hotfix] #276 - universityId, display name 변경
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
Labels: 🚨 review required 🚨, 💞 가현
