Repository Team-Hankki/hankki-iOS, pull requests merged in 2024-12, with the labels that each got.

#306 [Refactor] #288 - CreateZipTextField - Component 생성
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/CreateZipTextField/CreateZipTextField.swift
  Hankkijogbo/Hankkijogbo/Global/Components/CreateZipTextField/CreateZipTextFieldType.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
Labels: ♻️ Refactor, 🤹🏻‍♀️ 서현

#309 [Feat] #307 - Filtering category UICollectionView components
  Hankkijogbo/Hankkijogbo/Global/Extensions/UICollectionView+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_filtering_normal.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_filtering_normal.imageset/status=Default.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_filtering_selected.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_filtering_selected.imageset/status=filtered.svg
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 🍚 Feat, 💞 가현

#314 [Feat] #310 - Filtering Bottom Sheet
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetPriceFilterResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/FilteringBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
Labels: 🍚 Feat, 💞 가현

#322 [Design] #316 - 식당 상세 정보 UI 중 메뉴판과 유의사항 뷰
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_edit_detail.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_edit_detail.imageset/ic_edit_detail.svg
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiDetailResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiEditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiMenuFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiMenuHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/DetailMapView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiInfoView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiMenuCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/PrecautionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/EditHankkiBottomSheetViewController.swift
Labels: 🎨 Design, 🐬 은수

#323 [Feat] #317 - 식당 정보 다를 시 제보 화면 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/BottomButtonView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiMenuFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiMenuHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/RemoveHankkiViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/RemoveHankki/View/Cell/RemoveOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/RemoveHankki/View/RemoveHankkiViewController.swift
  Hankkijogbo/Hankkijogbo/Present/RemoveHankki/View/RemoveOptionCollectionView.swift
Labels: 🍚 Feat, 🎨 Design, 🐬 은수

#324 [Feat] #315 - Home Filtering BottomSheet 연결
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiLineView/CustomLineView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/FilteringBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🍚 Feat, 💞 가현

#321 [Feat] #308 - 족보 공유 기능
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Application/AppDelegate.swift
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/BottomButtonView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/URL+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_selected_list.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_selected_list.imageset/btn_heart.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_selected_list.imageset/ic_heart.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Config.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetSharedZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetZipOwnershipResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewControllerType.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/TagTextField.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/BaseHankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipFooterTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewControllerType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/ZipDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#326 [Fix] #325 - HankkiList내 HankkiDetail 생성자 변경사항 반영
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/BaseHankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현
