Repository Team-Hankki/hankki-iOS, pull requests merged in 2024-07, with the labels that each got.

#11 [Add] #9 - 에셋 추가 및 리드미 수정
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_filled.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_filled.imageset/Frame 52.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_filled.imageset/Frame 52@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_filled.imageset/Frame 52@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_empty.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_empty.imageset/Property 1=Default.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_empty.imageset/Property 1=Default@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_empty.imageset/Property 1=Default@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_filled.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_filled.imageset/Property 1=Variant2.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_filled.imageset/Property 1=Variant2@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_check_filled.imageset/Property 1=Variant2@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_empty.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_empty.imageset/Property 1=btn_like_lined.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_empty.imageset/Property 1=btn_like_lined@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_empty.imageset/Property 1=btn_like_lined@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_filled.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_filled.imageset/Property 1=btn_like_filled.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_filled.imageset/Property 1=btn_like_filled@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_filled.imageset/Property 1=btn_like_filled@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_empty.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_empty.imageset/Group 176.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_empty.imageset/Group 176@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_empty.imageset/Group 176@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_filled.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_filled.imageset/Property 1=btn_plus_filled.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_filled.imageset/Property 1=btn_plus_filled@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_plus_filled.imageset/Property 1=btn_plus_filled@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_empty.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_empty.imageset/status=btn_radio_default.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_empty.imageset/status=btn_radio_default@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_empty.imageset/status=btn_radio_default@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_filled.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_filled.imageset/status=btn_radio_selected.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_filled.imageset/status=btn_radio_selected@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_radio_filled.imageset/status=btn_radio_selected@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_target.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_target.imageset/btn_target.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_target.imageset/btn_target@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_target.imageset/btn_target@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray100.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray200.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray300.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray400.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray50.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray500.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray600.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray700.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray800.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray850.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Gray900.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Red.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/RedLight.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/White.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Yellow.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/YellowLight.colorset/Contents.json
  README.md
Labels: + Add, 🔧 Chore, 💞 가현

#12 [Add] #10 - Font 추가 및 PR TEMPLATE 수정
  .github/PULL_REQUEST_TEMPLATE.md
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIFont+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/Pretendard/Pretendard-Bold.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/Pretendard/Pretendard-Medium.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/Pretendard/Pretendard-Regular.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/Pretendard/Pretendard-SemiBold.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/SUITE/SUITE-Bold.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/SUITE/SUITE-Medium.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/SUITE/SUITE-Regular.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/SUITE/SUITE-SemiBold.otf
  Hankkijogbo/Hankkijogbo/Global/Resources/Fonts/a.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Present/ViewController.swift
Labels: + Add, 🐬 은수

#21 [Feat] #15 - Custom TabBar, NavigationBar
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/AppDelegate.swift
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarItem.swift
Labels: 🍚 Feat, 💞 가현

#25 [Chore] #23 - 라이브러리 import
  Hankkijogbo/Hankkijogbo/Present/Base/BaseCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseView.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
Labels: 🔧 Chore, 💞 가현

#19 [Feat] #16 - Alert Custom
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertStyle.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#27 [Chore] #20 - Font 행간 설정, Font 추가, Color assets 이름바꾸기
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIFont+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UILabel+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/HankkiRed.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/HankkiRedLight.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/HankkiWhite.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/HankkiYellow.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/HankkiYellowLight.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
Labels: 🎨 Design, 🤹🏻‍♀️ 서현

#26 [Feat] #17 - ToastView Custom
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/BlackToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/WhiteToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIButton+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIScreen+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Present/ViewController.swift
Labels: 🍚 Feat, 🐬 은수

#29 [Feat] #28 - Univ Select View
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/HankkiRedLight2.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#31 [Feat] #18 - 나의 식당 족보 바텀시트 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseCollectionReusableView.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListHeaderView.swift
Labels: 🍚 Feat, 🐬 은수

#36 [Feat] #30 - Mypage View
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarItem.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHankkiCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageQuitFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageZipCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#45 [Feat] #38 - 전체 식당 리스트 BottomSheet
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Present/Home/Model/TotalListModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListCollectionViewCell.swift
Labels: 🍚 Feat, 💞 가현

#42 [Feat] #33 - ZipList View Controller
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCellDataStruct.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#49 [Feat] #32 - 제보하기 기본 UI 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiCompositionalLayout/CompositionalLayoutFactory.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiReusableView/BufferFooterView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/WhiteToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarItem.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/AddMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/ImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/ReportCompositionalLayoutFactory.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/ReportHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/SearchCollectionViewCell.swift
  Hankkijogbo/Podfile.lock
  Hankkijogbo/Pods/Manifest.lock
  Hankkijogbo/Pods/Pods.xcodeproj/project.pbxproj
  Hankkijogbo/Pods/Target Support Files/Pods-Hankkijogbo/Pods-Hankkijogbo-frameworks.sh
Labels: 🍚 Feat, 🐬 은수

#50 [Feat] #48 - MyZip, Reported&Liked Hankki List
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UILabel+.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCellDataStruct.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewControllerType.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Pods/Pods.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#53 [Feat] #46 - 식당 검색 화면, 이미지 첨부 화면 및 식당 종류 셀 클릭 액션 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiReusableView/BufferFooterView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiReusableView/BufferView.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UITextField+.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/AddMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportCompositionalLayoutFactory.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SelectImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/View/CategoryCollectionViewCell.swift
Labels: 🍚 Feat, 🐬 은수

#52 [Feat] #51 - Create Zip View
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/MainButton.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/TagTextField.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#60 [Delete] #56 - LoginView Error Fix
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Present/Login/LoginViewController.swift
Labels: 🛠️ Fix

#55 [Feat] #47 - 필터링 CollectionView, DropDown Custom
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/ButtonType.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_back.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_back.imageset/Element_All.svg
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/Model/FilteringModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SelectImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Pods/Pods.xcodeproj/project.pbxproj
Labels: 🍚 Feat, 💞 가현

#62 [Feat] #56 - Login View
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Hankkijogbo.entitlements
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#63 [Feat] #61 - CoreLocation 위치 정보 허용
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarItem.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🍚 Feat, 💞 가현

#66 [Feat] #54 - 메뉴 이름 및 가격, 메뉴 추가 쪽 관련 액션 및 디테일 추가
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Extensions/String+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UICollectionView+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIResponder+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UITextField+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/AddMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🍚 Feat, 🐬 은수

#72 [Chore] #65 - Conflict 해결
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#71 [Setting] #68 - Network 초기 세팅
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Resources/Config.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Network/Base/BaseAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/URLConstant.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/GetHankkiListRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetCategoryFilterResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Home/DTO/Request/request.swift
  Hankkijogbo/Hankkijogbo/Network/Home/DTO/Response/response.swift
  Hankkijogbo/Hankkijogbo/Network/Home/HomeAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Home/HomeTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: ⚙️ Setting, 💞 가현

#74 [Feat] #67 - 식당 세부 정보 UI 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/HankkiDetailButton.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiPaddingLabel/HankkiPaddingLabel.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/WhiteToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/CATransition+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_back_white.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_back_white.imageset/ic_chevron left.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@1x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@3x.png
  Hankkijogbo/Hankkijogbo/Network/Base/BaseAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/URLConstant.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/Model/HankkiInfoDummy.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiEditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListCollectionViewCell.swift
Labels: 🍚 Feat, 🐬 은수

#78 [Network] #76 - Report, Location Service 세팅
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Network/Base/BaseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Location/DTO/Response/GetSearchedLocationResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Location/LocationAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Location/LocationTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Report/DTO/Response/GetReportedNumberResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Report/ReportAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Report/ReportTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseModel.swift
Labels: 🐬 은수, 🛜 Network

#81 [Feat] #58 - 식당 제보(등록) 완료 UI 구현
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_create_screen1.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_create_screen1.imageset/img_create_screen1.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_create_screen2.imageset/img_create_screen2.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_create_screen2.imageset/img_create_screen2@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_create_screen2.imageset/img_create_screen2@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_orange_gradient.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_orange_gradient.imageset/Ellipse 632.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_orange_gradient.imageset/Ellipse 632@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_orange_gradient.imageset/Ellipse 632@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_store.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_store.imageset/img_store.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_store.imageset/img_store@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Create/img_store.imageset/img_store@3x.png
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/HankkiInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
Labels: 🍚 Feat, 🐬 은수

#82 [Network] #75 - Home 필터링 API 연결
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetPriceFilterResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetSortOptionFilterResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 💞 가현, 🛜 Network

#83 [Network] #73 - Auth, User, Zip, University Service 추가
  .gitignore
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/DTO/Request/AuthRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/DTO/Response/AuthResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/University/DTO/Response/GetUniversityListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/University/UniversityService.swift
  Hankkijogbo/Hankkijogbo/Network/University/UniversityTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Request/PostMeUniversityRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeHankkiHeartListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeStoresReportsResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeUniversityResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/DeleteZipToHankkRequestiDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/PostZipBatchDeleteRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/PostZipToHankkiRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#87 [Network] #80 - 로그인, 로그아웃, 대학 선택 API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/URLConstant.swift
  Hankkijogbo/Hankkijogbo/Network/University/UniversityService.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#86 [Docs] #70 - Readme 수정
  README.md
Labels: 📄 Docs, 🤹🏻‍♀️ 서현

#91 [Network] #84 - 이미지 API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIImageView+.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/GetHankkiListRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetCategoryFilterResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetPriceFilterResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetSortOptionFilterResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 💞 가현, 🛜 Network

#96 [Fix] #93 - 오류 해결
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🚨 review required 🚨, 💞 가현

#95 [Network] #79 - 식당 제보수 조회 API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/Report/DTO/Response/GetReportedNumberResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Report/ReportAPIService.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
Labels: 🐬 은수, 🛜 Network

#94 [Network] #88 - Mypage api 연결
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeStoresReportsResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewControllerType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageZipCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCellDataStruct.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#99 [Network] #89 - 장소 검색 관련 API 연동 및 데이터 바인딩 완료
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDebouncer/HankkiDebouncer.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiValidateRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Location/DTO/Response/GetSearchedLocationResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Location/LocationAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Report/ReportAPIService.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🐬 은수, 🛜 Network

#100 [Network] #97 - 식당 세부 조회 API 연동 완료
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiDetailResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Pods/Pods.xcodeproj/project.pbxproj
Labels: 🐬 은수, 🛜 Network

#106 [Network] #101 - 식당 좋아요 추가 및 삭제 API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/HeartResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
Labels: 🐬 은수, 🛜 Network

#104 [Network] #90 - 족보 관련 API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/University/DTO/Response/GetUniversityListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/DeleteZipToHankkRequestiDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/PostZipRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageQuitFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#107 [Network] #103 - 사용자 족보 목록 바텀시트뷰 API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_disable.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_disable.imageset/img_list_plus_disabled_ios.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_disable.imageset/img_zip_create_disable.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_disable.imageset/img_zip_create_disable@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_disable.imageset/img_zip_create_disable@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_normal.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_normal.imageset/img_zip_create_normal.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_normal.imageset/img_zip_create_normal.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_normal.imageset/img_zip_create_normal@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_create_normal.imageset/img_zip_create_normal@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail1.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail1.imageset/img_zip_thumbnail1.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail1.imageset/img_zip_thumbnail1.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail1.imageset/img_zip_thumbnail1@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail1.imageset/img_zip_thumbnail1@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail2.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail2.imageset/img_zip_thumbnail2.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail2.imageset/img_zip_thumbnail2.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail2.imageset/img_zip_thumbnail2@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail2.imageset/img_zip_thumbnail2@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail3.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail3.imageset/img_zip_thumbnail3.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail3.imageset/img_zip_thumbnail3.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail3.imageset/img_zip_thumbnail3@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail3.imageset/img_zip_thumbnail3@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail4.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail4.imageset/img_zip_thumbnail4.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail4.imageset/img_zip_thumbnail4.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail4.imageset/img_zip_thumbnail4@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Zip/img_zip_thumbnail4.imageset/img_zip_thumbnail4@3x.png
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetMyZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/ViewModel/MyZipViewModel.swift
Labels: 🐬 은수, 🛜 Network

#109 [Network] #108 - 족보에 식당 추가 API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/PostHankkiToZipRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/PostZipToHankkiRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/ViewModel/MyZipViewModel.swift
Labels: 🐬 은수, 🛜 Network

#111 [Network] #105 - Univ Select API 연동
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Network/University/DTO/Response/GetUniversityListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Request/PostMeUniversityRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/Model/UniversityModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#117 [Network] #114 - 필터링 실시간 업데이트
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 🛠️ Fix, 🚨 review required 🚨, 💞 가현

#121 [Fix] #118 - 위치 정보 디테일 수정
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_pin.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_pin.imageset/img_pin.svg
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🛠️ Fix, 💞 가현

#115 [Network] #110 - 식당 제보하기 기능 완료
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiDetailResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/PostHankkiResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/ViewModel/MyZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🐬 은수, 🛜 Network

#125 [Setting] #124 - App Logo 등록
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/1024.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/114.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/120.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/180.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/29.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/40.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/57.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/58.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/60.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/80.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/87.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: ⚙️ Setting, 💞 가현

#127 [Feat] #122 - Hankki Detail 이동 연결
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#129 [Feat] #126 - ShowAlert 에러 처리
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/ViewModel/MyZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: 🍚 Feat, 💞 가현

#130 [Network] #128 - HankkiList Heart API 연동
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#135 [Design] #134 - 모달 이미지 변경
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
Labels: 🎨 Design, 🤹🏻‍♀️ 서현

#137 [Chore] #132 - 사소한 UI 디테일 수정 및 오류 해결
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo.xcodeproj/xcshareddata/xcschemes/Hankkijogbo.xcscheme
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 🛠️ Fix, 🎨 Design, 🚨 review required 🚨, 💞 가현

#136 [Feat] #123 - 화면 연결 및 디테일 수정
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/BottomButtonView.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_detail.imageset/Frame 52.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@1x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@3x.png
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiPinResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiThumbnailResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Request/DeleteZipToHankkRequestiDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetMyZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCellDataStruct.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/ViewModel/MyZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🍚 Feat, 🐬 은수

#138 [Docs] #131 - Readme 수정
  README.md
Labels: 📄 Docs, 🤹🏻‍♀️ 서현
