Repository Team-Hankki/hankki-iOS, pull requests merged in 2024-08, with the labels that each got.

#141 [Fix] #140 - 코드 수정 및 디자인 수정
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Present/Home/Model/FilteringModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/Model/HomeModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/Model/TotalListModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
Labels: 🛠️ Fix, 🔧 Chore, 💞 가현

#145 [Fix] #144 - Auth Target Type, Zip Target Type 수정
  Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/DTO/Request/AuthRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Onboarding/View/OnboardingViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#149 [Fix] #148 - 공용 컴포넌트 생성
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiCategoryTagLabel/HankkiCategoryTagLabel.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
Labels: 🛠️ Fix, 💞 가현

#151 [Refactor] #142 - 1차 코드 개선 (제보하기 부분)
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/img_black_gradient.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/img_black_gradient@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/img_black_gradient@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@1x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/blackGradient.imageset/blackGradient@3x.png
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/Model/HankkiInfoDummy.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SelectImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, ♻️ Refactor, 🐬 은수

#154 [Refactor] #152 - Network State 분기처리 통합
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Network/University/UniversityService.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: ♻️ Refactor, 🤹🏻‍♀️ 서현, 🛜 Network

#156 [Network] #155 - Login View 로직 수정, Refresh Token 로직추가
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Onboarding/View/OnboardingViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: ♻️ Refactor, 🤹🏻‍♀️ 서현, 🛜 Network

#160 [Fix] #153 - 1차 자체 QA 반영
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/BlackToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/WhiteToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_lined_disabled.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_lined_disabled.imageset/btn_add_lined_disabled.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_create_my_zip.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_create_my_zip.imageset/img_food_my_plus.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_1.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_1.imageset/img_food_my_1.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_2.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_2.imageset/mg_food_my_2.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_3.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_3.imageset/mg_food_my_3.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_4.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_4.imageset/mg_food_my_4.svg
  Hankkijogbo/Hankkijogbo/Global/Utils/HankkiDebouncer.swift
  Hankkijogbo/Hankkijogbo/Global/Utils/ImageCompressor.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiEditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/ViewModel/MyZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/HankkiInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/AddMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SelectImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
Labels: 🍚 Feat, 🛠️ Fix, 🔧 Chore, 🐬 은수

#159 [Fix] #157 - 자체 QA 반영
  Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#166 [Fix] #143 - 자체 QA 1차
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🛠️ Fix, 💞 가현

#163 [Fix] #161 - 2차 자체 QA 반영 (사실 그냥 각종 수정사항 반영)
  Hankkijogbo/Hankkijogbo/Global/Components/EmptyView/EmptyView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/HankkiDetailButton.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UILabel+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/Rectangle 40882.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/Rectangle 40882@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/Rectangle 40882@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/img_black_gradient.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/img_black_gradient@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Detail/img_black_gradient.imageset/img_black_gradient@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Report/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Report/img_report_category.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Report/img_report_category.imageset/img_report_category.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Report/img_report_category.imageset/img_report_category@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Report/img_report_category.imageset/img_report_category@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_orange_gradient.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_orange_gradient.imageset/Ellipse 632.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_orange_gradient.imageset/Ellipse 632@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_orange_gradient.imageset/Ellipse 632@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_store.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_store.imageset/img_store.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_store.imageset/img_store@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/ReportComplete/img_store.imageset/img_store@3x.png
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiEditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/HankkiInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#169 [Network] #168 - 통신에러 클라이언트에서 표시
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/BlackToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#172 [Design] #170 - Design 수정사항 반영
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertStyle.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/MainButton.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_mypage_profile_default.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_mypage_profile_default@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_mypage_profile_default@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Gifs/loading.json
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
Labels: 🍚 Feat, 🎨 Design, 🤹🏻‍♀️ 서현

#173 [Fix] #167 - 자체 QA 2차
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIFont+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_normal.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_normal.imageset/Property 1=default.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_normal.imageset/status=default.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_selected.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_selected.imageset/Property 1=selected.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_selected.imageset/status=selected.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_normal.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_normal.imageset/Property 1=default (1).svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_normal.imageset/status=default (1).svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_selected.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_selected.imageset/Property 1=selected (1).svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_selected.imageset/status=selected (1).svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_report.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_report.imageset/_btn_jaebo.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_report.imageset/jaebo.svg
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
Labels: 🛠️ Fix, 💞 가현

#174 [Fix] #164 - 3차 자체 QA 반영
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiLineView/DottedLineView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/String+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UILabel+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiFromOtherRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiValidateRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/HeartResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/PostHankkiResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/PostHankkiValidateResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Location/DTO/Response/GetSearchedLocationResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Report/DTO/Response/GetReportedNumberResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetMyZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/Model/HankkiCategoryModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#177 [Design] #175 - 바뀐 디자인 시스템 반영
  Hankkijogbo/Hankkijogbo/Global/Components/EmptyView/EmptyView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/BottomButtonView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/HankkiDetailButton.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/MainButton.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/MoreButton.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiCategoryTagLabel/HankkiCategoryTagLabel.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/BlackToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/WhiteToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIFont+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Red100.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Red300.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Red400.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Red500.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Yellow100.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Yellow300.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Yellow400.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Colors.xcassets/Yellow500.colorset/Contents.json
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiEditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewControllerType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHankkiCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageQuitFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageZipCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Onboarding/Model/OnboardingModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/HankkiInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/AddMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/CategoryCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SelectImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCellModel.swift
Labels: + Add, 🎨 Design, 🤹🏻‍♀️ 서현

#180 [Fix] #176 - 3차 자체 QA
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
Labels: 🛠️ Fix, 💞 가현

#179 [Fix] #178 - 2차 자체 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_normal_52.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_normal_52.imageset/btn_heart-1.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_selected_52.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_selected_52.imageset/Property 1=filled.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_like_selected_52.imageset/btn_heart.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_mypage_profile_default 1.png
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
Labels: 🛠️ Fix, 🔧 Chore, 🤹🏻‍♀️ 서현

#183 [Design] #182 - Navigation Position, Font Custom
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🎨 Design, 🤹🏻‍♀️ 서현

#185 [Design] #184 - Home Default image
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIImageView+.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiThumbnailResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
Labels: 🎨 Design, 🤹🏻‍♀️ 서현

#189 [Fix] #188 - HankkiListViewModel Cell Model 변경
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeHankkiListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetZipListResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#191 [Fix] #181 - 1차 디자인 QA
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiCategoryTagLabel/HankkiCategoryTagLabel.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_target.imageset/btn_target.svg
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 🛠️ Fix, 🎨 Design, 💞 가현

#194 [Fix] #187 - 1차 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiCompositionalLayout/CompositionalLayoutFactory.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportCompositionalLayoutFactory.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#192 [Fix] #190 - 1차 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/MoreButton.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIFont+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_add_gray.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_add_gray.imageset/add.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_add_gray.imageset/plus.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/HankkiList/img_zip_screen1.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/HankkiList/img_zip_screen1.imageset/Frame 1171276034.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/HankkiList/img_zip_screen1.imageset/Frame 1171276034@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/HankkiList/img_zip_screen1.imageset/Frame 1171276034@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/HankkiList/img_zip_screen1.imageset/img_hankkiList_screen1.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/HankkiList/img_zip_screen1.imageset/img_hankkiList_screen1@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/HankkiList/img_zip_screen1.imageset/img_hankkiList_screen1@3x.png
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/Cell/MypageHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCell.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#196 [Fix] #195 - Detail, Liked List 간 하트 수 연동
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  README.md
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#199 [Fix] #193 - 1차 기능 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIButton+.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/GetHankkiListRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/GetHankkiPinRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 🛠️ Fix, 💞 가현

#200 [Design] #197 - 1.5차 디자인 QA
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/BottomButtonView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiCategoryTagLabel/HankkiCategoryTagLabel.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiPaddingLabel/HankkiPaddingLabel.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_dropdown.imageset/btn_dropdown.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_target.imageset/btn_target.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_food_16.imageset/ic_food.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_heart.imageset/ic_heart.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_normal.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_normal.imageset/Frame 3.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_normal.imageset/status=default.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_selected.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_selected.imageset/Frame 4.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_home_selected.imageset/status=selected.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_normal.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_normal.imageset/btn_my.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_normal.imageset/status=default (1).svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_selected.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_selected.imageset/Frame 5.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_mypage_selected.imageset/status=selected (1).svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_1.imageset/img_food_my_1.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_2.imageset/mg_food_my_2.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_3.imageset/mg_food_my_3.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyZipList/img_my_zip_4.imageset/mg_food_my_4.svg
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailHeaderView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
Labels: 🎨 Design, 🤹🏻‍♀️ 서현

#201 [Fix] #198 - 1.5차 디자인 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiToasts/WhiteToastView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_detail_big.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_add_detail_big.imageset/Frame 52.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_cancle.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_cancle.imageset/cancel.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_delete_big.imageset/icon_close_big.svg
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/HankkiInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/AddMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ImageCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportCompositionalLayoutFactory.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SelectImageCollectionViewCell.swift
Labels: 🛠️ Fix, 🎨 Design, 💞 가현

#205 [Network] #204 - 바뀐 getMe DTO 반영
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeResponseDTO.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#207 [Network] #206 - validate api 수정 반영
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiValidateRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🤹🏻‍♀️ 서현, 🛜 Network

#209 [Hotfix] #208 - Podfile Reset
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Podfile.lock
  Hankkijogbo/Pods/Manifest.lock
  Hankkijogbo/Pods/Pods.xcodeproj/project.pbxproj
  Hankkijogbo/Pods/Pods.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Hankkijogbo/Pods/Target Support Files/Pods-Hankkijogbo/Pods-Hankkijogbo-frameworks.sh
Labels: 🛠️ Fix, 🚨 review required 🚨, 💞 가현

#211 [Fix] #210 - 1.5차 기능 QA 반영
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🛠️ Fix, 💞 가현

#214 [Fix] #212 - 기능 버그 픽스
  Hankkijogbo/Hankkijogbo/Global/Components/EmptyView/EmptyView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Onboarding/View/OnboardingViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, 💞 가현

#216 [Fix] #215 - ZipList Cell 재사용성 문제 해결
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#217 [Fix] #213 - 1.5차 기능 QA
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Request/PostMeUniversityRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeUniversityResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/Model/UniversityModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
Labels: 🛠️ Fix, 🐬 은수

#219 [Fix] #218 - 2차 QA 실시간 반영
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
  Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
Labels: 🛠️ Fix, 💞 가현

#221 [Fix] #220 - 검색 결과 엠티뷰 Label 레이아웃 수정
  Hankkijogbo/Hankkijogbo/Global/Components/EmptyView/EmptyView.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#225 [Feature] #222 - Loaing View Custom
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiButtons/MainButton.swift
  Hankkijogbo/Hankkijogbo/Global/Components/LoadingView/FullLoadingView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/LoadingView/LoadingViewType.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Auth/AuthTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Location/LocationAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Location/LocationTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Report/ReportAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Report/ReportTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/University/UniversityService.swift
  Hankkijogbo/Hankkijogbo/Network/University/UniversityTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/User/UserTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiReportOption/HankkiReportOptionFooterView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
Labels: 🍚 Feat, 🤹🏻‍♀️ 서현

#227 [Fix] #226 - Apple Login 유효성 검증
  Hankkijogbo/Hankkijogbo/Application/AppDelegate.swift
  Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#228 [Fix] #223 - 2차 QA
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
Labels: 🛠️ Fix, 💞 가현

#234 [Fix] #233 - Loading View Error 해결
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#235 [Fix] #232 - 마지막 자체 QA 전 사소한 수정사항 반영
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#239 [Fix] #238 - 3차 QA
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🛠️ Fix, 💞 가현

#240 [Fix] #236 - 릴리즈 전 마지막 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#241 [Fix] #237 - 릴리즈 전 자체 QA 반영
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#245 [Fix] #243 - 3.5차 QA 진행
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🛠️ Fix, 💞 가현

#247 [Fix] #246 - Amplitude 변경사항 반영
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarItem.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/AmplitudeLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Utils/SetAmplitude.swift
  Hankkijogbo/Hankkijogbo/Global/Utils/SetupAmplitude.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/ViewModel/MyZipViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
  Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#250 [Fix] #249 - Hankki List Cell Chips 짤리는 문제 해결
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현
