Repository Team-Hankki/hankki-iOS, pull requests merged in 2024-11, with the labels that each got.

#280 [Fix] #279 - Fixing infinite loading error
  Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#283 [Fix] #278 - 2차 스프린트 디자인 QA
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIButton+.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🛠️ Fix, 💞 가현

#285 [Design] #268 - Mypage, Create Zip QA 사항 반영
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_my_profile.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_my_profile@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_my_profile@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_mypage_profile_default 1.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_mypage_profile_default@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/MyPage/img_mypage_profile_default.imageset/img_mypage_profile_default@3x.png
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
Labels: 🎨 Design, 🤹🏻‍♀️ 서현

#287 [Fix] #284 - 2차 스프린트 기능 QA
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🛠️ Fix, 💞 가현

#286 [Feat] #282 - 메뉴 수정 및 삭제 화면 완료
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/DeleteMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/EnterMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/ModifyMenuTextField.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UITextField+.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIView+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_delete.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_delete.imageset/btn_delete.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_modify_menu.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Button/btn_modify_menu.imageset/btn_modify_menu.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_delete_complete.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_delete_complete.imageset/img_deleted_completed.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_delete_complete.imageset/img_deleted_completed@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_delete_complete.imageset/img_deleted_completed@3x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_modify_complete.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_modify_complete.imageset/img_edit_completed.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_modify_complete.imageset/img_edit_completed@2x.png
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/EditHankki/img_modify_complete.imageset/img_edit_completed@3x.png
  Hankkijogbo/Hankkijogbo/Network/Menu/DTO/Request/PatchMenuRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/DTO/Response/PostMenuResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/MenuAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/MenuTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Add/AddMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/AddMenu/AddMenuCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Complete/CompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Complete/MenuCompleteView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/Cell/EditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/EditMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/ModifyMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/EditMenu/ModifyMenuCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/EditMenu/ModifyMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/ViewModel/EditMenuViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/ViewModel/ModifyMenuViewModel.swift
Labels: 🍚 Feat, 🐬 은수

#291 [Fix] #273 - 2차 스프린트 디자인 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/DeleteMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/EnterMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/ModifyMenuTextField.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiEditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Add/AddMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/ModifyMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/EditHankkiBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
Labels: 🛠️ Fix, 🎨 Design, 🐬 은수

#293 [Fix] #292 - Home filtering, total list 초기화 방지 에러
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🛠️ Fix, 💞 가현

#294 [Fix] #289 - 2차 스프린트 기능 QA 반영
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/DeleteMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/EnterMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/ModifyMenuTextField.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/ModifyMenuTextFieldType.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiDetailResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/DTO/Request/MenuRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/DTO/Request/PatchMenuRequestDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/DTO/Response/MenuResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/DTO/Response/PostMenuResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/MenuAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/Menu/MenuTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiDetail/HankkiDetailCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Add/AddMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Complete/CompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Complete/MenuCompleteView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/Cell/EditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/EditMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/ModifyMenuViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/EditHankkiBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/ViewModel/AddMenuViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/ViewModel/EditMenuViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/ViewModel/ModifyMenuViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#296 [Feat] #295 - 족보 만들기 AccessoryView 적용
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAccessoryView/DeleteMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAccessoryView/EnterMenuAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/HankkiAccessoryView/HankkiAccessoryView.swift
  Hankkijogbo/Hankkijogbo/Global/Components/ModifyMenuTextField/ModifyMenuTextField.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/ModifyMenuViewController.swift
Labels: 🍚 Feat, 🐬 은수

#301 [Fix] #300 - 2차 스프린트 최종 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiMenu/View/Edit/Cell/EditMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🛠️ Fix, 🐬 은수

#303 [Fix] #302 - BottomSheet 확장 스크롤 위치 복원
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
Labels: 🛠️ Fix, 💞 가현

#305 [Hotfix] #304 - error hotfix
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
Labels: 🛠️ Fix, 🚨 review required 🚨, 💞 가현
