Repository Team-Hankki/hankki-iOS, pull requests merged in 2025-01, with the labels that each got.

#327 [Feat] #319 - 위경도로 식당 상세 지도 및 주소 띄우기
  Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Config.swift
  Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
  Hankkijogbo/Hankkijogbo/Network/Base/BaseTargetType.swift
  Hankkijogbo/Hankkijogbo/Network/Base/NetworkService.swift
  Hankkijogbo/Hankkijogbo/Network/Base/URLConstant.swift
  Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiDetailResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/NaverMap/DTO/Response/GetHankkiAddressResponseDTO.swift
  Hankkijogbo/Hankkijogbo/Network/NaverMap/NaverMapAPIService.swift
  Hankkijogbo/Hankkijogbo/Network/NaverMap/NaverMapTargetType.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/Cell/HankkiMenuCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/DetailMapView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiInfoView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiMenuCollectionView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
  Hankkijogbo/Hankkijogbo/Present/MyZipList/View/MyZipListBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
Labels: 🍚 Feat, 🐬 은수

#330 [Feat] #329 - 3차 스프린트 홈 Qa fix
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_add_zip_gray.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_add_zip_gray.imageset/ic_addjocbo.svg
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/FilteringBottomSheetViewController.swift
  Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
Labels: 🍚 Feat, 💞 가현

#331 [Fix] #328 공유기능 QA 반영
  Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Splash/img_splash_image_logo.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Splash/img_splash_image_logo.imageset/Frame 1171276100.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Splash/img_splash_text_logo.imageset/Contents.json
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Splash/img_splash_text_logo.imageset/Group 36242.svg
  Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Image/Splash/img_splash_text_logo.imageset/바뀐 한끼족보 스플래시.svg
  Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
  Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
Labels: 🛠️ Fix, 🤹🏻‍♀️ 서현

#333 [Fix] #332 - 3차 스프린트 식당 상세 QA 반영
  Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/DifferentInfoView.swift
  Hankkijogbo/Hankkijogbo/Present/HankkiList/View/BaseHankkiListViewController.swift
Labels: 🛠️ Fix, 🐬 은수
